### PR TITLE
BL-1204 Update qa workflow.

### PR DESCRIPTION
**Pull request by dkinzer**
* Deploy to qa on merges to master branch.
* Deploy to production on release.
* Keeps requires approval for deploys (Further guards against unintentional deploys).

### CODE REVIEW

**Comment by bibliotechy** [comment]
@dkinzer this looks like it is going to trigger a request for prod deploy on updates to master, which does not seem like what we want.

**Comment by dkinzer** [comment]
@bibliotechy I believe I believe Christina copied that directly from the tul_cob workflow config.  This update doesn't actually make changes to that step. But, it doesn't do anything on its own.  I guess because of the fact that it's a `type: approval` thing.

It will only get triggered by prod_deploy workflow which has that approval as a requirement.

**Comment by bibliotechy** [comment]
@dkinzer So every merge to master is going to trigger an approval for prod deploy that just sits there?

**Comment by dkinzer** [comment]
@bibliotechy  I don't think so. I have. not noticed that.  And that config's basically been there since we started using circleci.

**Pull request merged**
